os: Visual Studio 2017
platform: x64

test: off

#
# Build
#
build_script:
  #
  # Visual Studio (MSBuild)
  #
  - mkdir build_msbuild
  - cd build_msbuild
  - cmake -DENABLE_COVERAGE=1 -DSTANDALONE_TESTING=0 -G "Visual Studio 15 2017 Win64" ..
  - msbuild ci_opengl_template.sln
  - ctest -C Debug
  - cd ..
